### ISSUE TITLE
GPU fix seems to have started failing on latest High Sierra Updates

### ISSUE THREAD

**Issue by tfinneid** [julian-poidevin/MBPMid2010_GPUFix#120]
Hi

Lately my MacBook Pro has started failing again with the GPU fix applied. The circumstances are a bit unclear to me, but I will try to help analyse as much as I can.  I know the Mid2010 version is not supported for higher versions than High Sierra and will be unnsupported from Agugust 2020, but I am hopeful I can continue using it until then or even later.

The GPU fix worked fine on High Sierra since I started using it in August 2018, but sometime during the spring 2019, after a an update from Apple I started experiencing reboots again (for me the problem mostly manifested itself with reboots, with occasional black screens only). The problem is now not as frequent as it was before the I started using the gpufix, but happens once in a while.

As the documentation states I apply the pathc after every mac os update. And sometimes i have to apply the gpufix a second time, if it crashes and reboots. So two applications of the patch for it to work more permanently. 

It might of course not be a gpu problem this time, but seems to behave in the same manner as before I stared using the gpufix.

Is there a chance Apple changed things slightly, so that the gpufix needs an update to stay functional? Any help would be much appreciated.

**Comment by jurgenkoppen** [comment]
Hey Timmy, from what I understand you over write the GPU fix overtime you install a software update. This means you have to reinstall the patch every time you do such an update.

**Comment by julian-poidevin** [comment]
@tfinneid : @jurgenkoppen is right, it's written on the app README.md (on the main page...) :

![image](https://user-images.githubusercontent.com/8756421/67186652-cedc0a00-f3e8-11e9-9865-51a197a177ff.png)

**Comment by tfinneid** [comment]
I am sorry for the misunderstanding but the problem is not solved. As I state in the description I apply the patch after every mac os update. The issue is now that even with the patch applied, it starts failing again. Which it did not do previously.

Please reopen the bugreport. I edited to description to make it clearer that I do apply the patch again after every mac os update.

**Comment by julian-poidevin** [comment]
@tfinneid does the patcher says the patch succeeded ?

**Comment by tfinneid** [comment]
@julian-poidevin yes, the patcher do succeed. Is there any other log than the one in the main gpufix application window or is there some profiling or similar I could do when applying the patch the next times?

**Comment by 21Slingshot** [comment]
I am experiencing the same issue - but on Sierra. Installed the latest software update and reapplied the patch (successfully installed) and the reboots/black screens have been happening to me as well. I even tried to apply twice - going through the process all over again in terminal, etc...

**Comment by 21Slingshot** [comment]
update: installed it again and it seems to work. 3rd times a charm!

**Comment by tfinneid** [comment]
I dont understand, why is this bug report closed? As far as I can see there is no new version that fixes the problem, and what @21Slingshot is saying supports this bug report. That something has changed in the OS, presumably in later updates of MacOS editions. The patch must be applied several times, after each OS update, before becoming effective. I am sure that is not what is desired. It should be enough to apply the patch once, after each OS update, not 2-3 times. Why does the patch not work the first or second time it was applied?

**Comment by tfinneid** [comment]
@julian-poidevin, please respond to my question. The bug is not properly addressed and I would like to understand why you think closing this bug report solves the bug. 

I am willing to help trying to debug the problem, but for that to happen I need your assistance.

**Comment by Bl2c5FlA9** [comment]
My MacBook has been upgraded to Sierra, not High Sierra.  I do sometimes see the patch "fail" and then I have to re-install it.  It may be that High Sierra has changed something to do with updates - meaning it "sees" the fact that you have changed a system file and hence does an unannounced update to correct that problem.  I suspect that happens every now and then on my Mac, because I have not been notified that a typical update needs to be installed.  Would it surprise you that Apple does something like that?

Note too that your laptop is ancient (as is mine).  The only long-term fix is to buy a current machine.  I am not happy about that either but I know that destiny awaits me.

If you have the skills and patience to determine why the patch is failing there are many Mac users who will cheer you on to discover what is happening and fix it.  In the meantime you might check to verify that "auto updates" are disabled.  And to determine if some kind of update is happening when you have not been notified.  While I cannot prove it I believe that happens now and then on my Mac.

**Comment by julian-poidevin** [comment]
@tfinneid Well, @Bl2c5FlA9 has said everything I guess. Thanks for answering @Bl2c5FlA9, I totally share your point.
