### ISSUE TITLE
SIP enable

### ISSUE THREAD

**Issue by Max691** [julian-poidevin/MBPMid2010_GPUFix#126]
Can I re-enable SIP with the command "csrutil enable without ..." and what have I to write instead of ...
(I feel a littel bit unsafe with disabled SIP)

**Comment by julian-poidevin** [comment]
@Max691 You can re-enable SIP with the following command `csrutil enable` then you can check SIP status typing `csrutil status`.

Though I would not recommend re-enabling SIP because the MBPMid2010 patch has to be apply each time you mac performs a system update and it's often... So you would have to disable SIP each time...

**Comment by Max691** [comment]
I know but can i enabel SIP partially with "csrutil enabel without ...(your Programm)"?

**Comment by julian-poidevin** [comment]
No I'm sorry that's not possible.
