### ISSUE TITLE
Not compatible with 17" version

### ISSUE THREAD

**Issue by gazoo92** [julian-poidevin/MBPMid2010_GPUFix#24]
I have a mid-2010 Macbook Pro 17" and I get the error "Sorry your Mac is not compatible. The application will close."

I have the same graphics problem which makes my computer crash constantly, even with gfxCardStatus. It won't even start up at times and gets stuck in a reboot loop. Terrible!

**Comment by julian-poidevin** [comment]
Hi. I search around the web for this problem but all I see is about the 15" model. I'm not sure if the origin of the problem on 17" is the same, and so, if the program I provid will help to fix the issue 😕. If you want, I can provide you a custom version of the program but since I can't test it, you should use it **at your own risks**. I will not support 17" models in the app if I'm not sure it works properly. Is that solution suits you? If so, I'll find a way to send you the custom app.

**Comment by gazoo92** [comment]
Julian,

Thank you so much. I understand the risk but I am desperate to get rid of the problem. Once I test it, I will let you know if it fixes it.

For reference, my "bad" GPU is the NVIDIA GeForce GT 330M which I believe is the same as the 15"

**Comment by gazoo92** [comment]
I can give you my email address

**Comment by julian-poidevin** [comment]
Ok, here's a version of the application with no limitations and tests on hardware : 
- [MBPMid2010-GPU-Fix-0.5.x-custom](https://mega.nz/#F!P4QiwbwZ!CgSxZ81Doiqa8-yz3_w64w
)

Even though there are some risks, I added error recognition while patching since version [v0.3.0](https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/CHANGELOG.md#030-may-6th-2017). So if the kernel extension file is not the same pattern on 15" and 17", the modification will not be applied to your mac.

Please tell me if that worked.

Thanks

**Comment by gazoo92** [comment]
Hi Julian,

Thank you. I downloaded it and it patched succesfullly.

Unfortunately my computer wont even start up now. It doesn't even go beyond the apple screen. It just crashes or shuts down.

Any advice on what to do?

**Comment by julian-poidevin** [comment]
Oh shit, sorry about that. Try using recovery mode explained here : https://apple.stackexchange.com/a/43129

> Reboot your Mac. When you hear the boot chime, hold the COMMAND + R keys. You will enter the Lion Recovery environment. From there, simply choose to reinstall Lion. It will simply remove the current system and replace it with a fresh copy. **None of your data will be deleted or moved**. The only thing that will be replaced will be the core system files. There is no longer any need to make backups, migrate your data, or mess with partitioning.
If you'd like to read more about the Lion Recovery function, go here: http://support.apple.com/kb/HT4718

**Comment by gazoo92** [comment]
Julian,

Not your fault. I did it at my own risk.

Unfortunately I can't even go into recovery mode. The computer crashes halfway at the loading screen.

In fact, in order to disable SIP for the patch, I had to boot up by holding down the Command-R-S keys. Only then was I able to disable SIP.

Any other ideas?

**Comment by julian-poidevin** [comment]
Can you tell me on which OS you are ?

Did you try to use Command-R-S keys to boot up instead of Command + R.

**Comment by julian-poidevin** [comment]
Did you try to boot on Safe Mode : https://support.apple.com/en-us/HT201262

**Comment by gazoo92** [comment]
Sorry, I am on El Capitan.

When I use Command-R-S keys, it goes to a terminal window. How do I use it to boot up?

I just tried Safe Mode and it works but I had to reboot the computer over 40 times just to let me boot in Safe Mode. If I restart the computer, it will likely fail again.

**Comment by julian-poidevin** [comment]
It's good if you have a terminal window, please type the following command :
```Shell
sudo rm -rf /System/Library/Extensions/AppleGraphicsPowerManagement.kext
```

**Comment by gazoo92** [comment]
Thank you Julian

I will try it

**Comment by gazoo92** [comment]
I tried the sudo command but it says it doesn't recognize it.

**Comment by gazoo92** [comment]
I was able to do the sudo command. I will reboot the computer and let you know the result.

**Comment by julian-poidevin** [comment]
Were you able to fix the problem ? Thanks.

**Comment by gazoo92** [comment]
Hey Julian

Thanks for asking. Yes I was able to reverse the patch.

However I am still having problem with the computer not being able to boot up or the screen going black when loading it up. I have to try 15-20 times before the computer finally boots up.

Is there no way to permanently disable the discreet video card? 

I can live with just the Intel card as long as the computer works. gfxCardStatus only kicks in after the computer has already booted up.

**Comment by gazoo92** [comment]
Julian,

Y

**Comment by julian-poidevin** [comment]
Sorry but I have absolutely no idea about how to fix your problem. Try posting on forums to get some help. Closing the issue.
