### ISSUE TITLE
[Question] Will this same trick works for MBP Mid-2012 nVedia GPU ?

### ISSUE THREAD

**Issue by popovkai** [julian-poidevin/MBPMid2010_GPUFix#31]
Cannot find a good solution for mid-2012 MBP ... ;-( ;-( ;-(
Try gfxCardStatus (even with the updated version for Sierra) but some applications will still trigger the GPU usage...

**Comment by julian-poidevin** [comment]
Seems to be an hardware problem also.
There is a possible software fix according to this thread : https://forums.macrumors.com/threads/gpu-panic-rmbp-mid-2012.2004595/

It consist in uninstalling default Nvidia Web drivers.

Also, I would like to let people use my software with other MBP but since I can't Beta test the software by myself I prefer not two. There is a high risk of "bricking" the Mac if things are not done correctly....
