### ISSUE TITLE
GPU panic on Mojave when waking up on battery

### ISSUE THREAD

**Issue by jimbojetlag** [julian-poidevin/MBPMid2010_GPUFix#98]
This kernel patch works great on Mojave so far. But recently I discovered that the GPU panic happens when waking up on battery (power cord disconnected).

```
*** Panic Report ***
panic(cpu 0 caller 0xffffff7f93a8d871): "GPU Panic: mux-regs 3 3 7f 0 0 0 severity 3 WS-ready 0 switch-state 0 IG FBs 0 EG FBs 1:0 power-state 0 3D idle HDA idle system-state 2 power-level 15:0 connect-change 0 : NVRM[0/1:0:0]: Read Error 0x00000100: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0xd2000000 0xffffff9131909000 0x0a5480a2, D0, P1/4\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGraphicsControl/AppleGraphicsControl-3.22.26/src/AppleMuxControl/kext/GPUPanic.cpp:170
```

**Comment by julian-poidevin** [comment]
Hi, were there any macOS update of your Mac since you applied the patch? The patch has to be applied after each update because it erases the file modified by my app.

**Comment by jimbojetlag** [comment]
@julian-poidevin there has been no update and the patch is definitely applied, without it the GPU kernel panic happens at login screen. There must have been some change in Mojave about waking up the GPU that this patch may not cover.

**Comment by heyitzaamir** [comment]
Exactly im getting this problem as well... Whenever I close my laptop and come back to it, it crashes as well as when I run an external monitor with my laptop, it crashes ☹️ so external monitor is a no no as of now, but all in all the patch works perfect, it's just when I close my laptop and open it back up, I gotta run the patch again, but what I really want to fix is letting it not crash while using my external monitor if theres any way to resolve that problem 🤔

**Comment by AndreasHnida** [comment]
@heyitzaamir I'm using my external monitor just fine. Ultra Wide 3440x1440. The thing is, it needs to be the only screen running. That means the laptop lid must be closed, so that there is only one display (the external monitor) active. I guess as soon as you use both displays the graphics card is no longer able to sustain a reduced power draw and therefore crashing. That's how this patch works. Putting the graphics card in "normal mode" preventing it to draw too much power because the panics come from a faulty condensator.

My problem with mojave is that it does not recognize my lid to be closed. So it always uses the second display regardless of it being closed or not. (Noticable when I move my mouse out of the left edge of my external screen) But running high sierra it works just fine. If your mojave installation recognizes the lid to be closed it should be no problem to use your external monitor instead of the macbook display. Just not both at the same time. 

Hope that helps.

**Comment by heyitzaamir** [comment]
ohh okay thank you so much bro

**Comment by htonal** [comment]
+1, I've been able to use the MacBook Pro 15-inch Mid2010 for several hours without issue
using an external monitor as single active display.
I would recommend to use the power adapter and to close the lid as soon as the power key has been pressed.

**Comment by ghost** [comment]
@htonal I have this problem as well on High Sierra. Can you please explain a bit more about the power adapter - (not sure how you would use that for this?), and the power key - do you mean the on/off button? 
Thanks!

**Comment by jimbojetlag** [comment]
For me it turned out to be a bluetooth problem causing the GPU kernel panic, this solved the panic for me for now:

Settings > Bluetooth > Advanced > uncheck: Allow Bluetooth devices to wake this computer

**Comment by julian-poidevin** [comment]
@jimbojetlag Can I close the issue ?

**Comment by jimbojetlag** [comment]
@julian-poidevin unfortunately the problem continues to exist. The bluetooth fix helped to reduce the chances, but never fixed it permanently.

**Comment by julian-poidevin** [comment]
I can't do much about that, sorry.
